# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  kindle-tool = {
    pname = "kindle-tool";
    version = "v1.6.6";
    src = fetchFromGitHub {
      owner = "NiLuJe";
      repo = "KindleTool";
      rev = "v1.6.6";
      fetchSubmodules = false;
      sha256 = "sha256-IelccR8b6btLiiJQ5gXyizSIgfZzQtztV5QT3eCHBms=";
    };
  };
  matrix-qq = {
    pname = "matrix-qq";
    version = "0.1.11";
    src = fetchFromGitHub {
      owner = "duo";
      repo = "matrix-qq";
      rev = "0.1.11";
      fetchSubmodules = false;
      sha256 = "sha256-8QY5rySBJ+FSH8uEHewFX7WqhpbzZL1+fMEduDPHu9U=";
    };
  };
  mdbook-epub = {
    pname = "mdbook-epub";
    version = "v0.4.48";
    src = fetchFromGitHub {
      owner = "Michael-F-Bryan";
      repo = "mdbook-epub";
      rev = "v0.4.48";
      fetchSubmodules = false;
      sha256 = "sha256-glSsItXPafdium87PbU0Tt/Qniud6xZzqDNeryFF8BQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-glSsItXPafdium87PbU0Tt_Qniud6xZzqDNeryFF8BQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  opencl-benchmark = {
    pname = "opencl-benchmark";
    version = "v1.9";
    src = fetchFromGitHub {
      owner = "ProjectPhysX";
      repo = "OpenCL-Benchmark";
      rev = "v1.9";
      fetchSubmodules = false;
      sha256 = "sha256-hI1FR9M4Yz5NrFLiX04q6nsA5Eu3uFLIHQ/Ekh7KHdo=";
    };
  };
  pandoc-static-amd64 = {
    pname = "pandoc-static-amd64";
    version = "3.9";
    src = fetchTarball {
      url = "https://github.com/jgm/pandoc/releases/download/3.9/pandoc-3.9-linux-amd64.tar.gz";
      sha256 = "sha256-zU/UCIBuBcGOLj6leXJebPzsa8oGC+JUAyhBqdzKdto=";
    };
  };
  pandoc-static-arm64 = {
    pname = "pandoc-static-arm64";
    version = "3.9";
    src = fetchTarball {
      url = "https://github.com/jgm/pandoc/releases/download/3.9/pandoc-3.9-linux-arm64.tar.gz";
      sha256 = "sha256-s8XYlcbWYUKuMCHezoxZKpJfUjr6PAHZgL/gszGc3ok=";
    };
  };
  piqueserver = {
    pname = "piqueserver";
    version = "4e515c0250a90d03640003f318a45308e4765a30";
    src = fetchFromGitHub {
      owner = "piqueserver";
      repo = "piqueserver";
      rev = "4e515c0250a90d03640003f318a45308e4765a30";
      fetchSubmodules = false;
      sha256 = "sha256-vzUjby+/lImdPXnaqibXbtkRz/TU+RJn3jol0EZvsAo=";
    };
    date = "2026.02.05";
  };
  pyenet = {
    pname = "pyenet";
    version = "1.3.17";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pyenet/pyenet-1.3.17.tar.gz";
      sha256 = "sha256-gOGWDztJfuYB1gnakdwHPCu6jn8FUotnIGuKoM5PGmo=";
    };
  };
  rescript-language-server = {
    pname = "rescript-language-server";
    version = "1.72.0";
    src = fetchFromGitHub {
      owner = "rescript-lang";
      repo = "rescript-vscode";
      rev = "1.72.0";
      fetchSubmodules = false;
      sha256 = "sha256-bGCQ/HC6ItQMR0v0wLsF9pNX/Y1sBnp7E+Am0flWhGk=";
    };
  };
  rime-table-bin-decompiler = {
    pname = "rime-table-bin-decompiler";
    version = "c722c060f77c3895564d40bd7e3f44a2b315ee7c";
    src = fetchFromGitHub {
      owner = "kitty-panics";
      repo = "rime-table-bin-decompiler";
      rev = "c722c060f77c3895564d40bd7e3f44a2b315ee7c";
      fetchSubmodules = false;
      sha256 = "sha256-2j9c9m4DvsI7jb6RnGiVtzig2qSVRCZEJL47h0Qe09o=";
    };
    date = "2022-10-30";
  };
  rust-async-book = {
    pname = "rust-async-book";
    version = "2dd70d7bf916b4f2dd37a4f2229c33809a850e97";
    src = fetchFromGitHub {
      owner = "rust-lang";
      repo = "async-book";
      rev = "2dd70d7bf916b4f2dd37a4f2229c33809a850e97";
      fetchSubmodules = false;
      sha256 = "sha256-KSl7fYUKf0Az0eHHxsltKyN/SEGV2kTo/tJsNkQLj3U=";
    };
    date = "2025-11-03";
  };
  rust-reference = {
    pname = "rust-reference";
    version = "76016c64f53e6fad861933da3b2cf5bd64dc9b20";
    src = fetchFromGitHub {
      owner = "rust-lang";
      repo = "reference";
      rev = "76016c64f53e6fad861933da3b2cf5bd64dc9b20";
      fetchSubmodules = false;
      sha256 = "sha256-Qiaw5pGFMeyt9gGrxzfudmh3x2reMF+OMlLJdKNbUN8=";
    };
    date = "2026-03-13";
  };
  rust-rfcs = {
    pname = "rust-rfcs";
    version = "c143e315774f746d667c5eecd95a8ed999e8a729";
    src = fetchFromGitHub {
      owner = "rust-lang";
      repo = "rfcs";
      rev = "c143e315774f746d667c5eecd95a8ed999e8a729";
      fetchSubmodules = false;
      sha256 = "sha256-gXhKfspzm0gOJSI9yI2TERNQvRiGHIxuZbLtKg1o+bc=";
    };
    date = "2026-01-31";
  };
  torrent-file-editor = {
    pname = "torrent-file-editor";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "torrent-file-editor";
      repo = "torrent-file-editor";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-k4sPotzlL9lkldlw6owA17iUuyrBY1dH89jGwtBcGVU=";
    };
  };
  transfersh = {
    pname = "transfersh";
    version = "v1.6.1";
    src = fetchFromGitHub {
      owner = "dutchcoders";
      repo = "transfer.sh";
      rev = "v1.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-V8E6RwzxKB6KeGPer5074e7y6XHn3ZD24PQMwTxw5lQ=";
    };
  };
  ufs-utils = {
    pname = "ufs-utils";
    version = "v7.14.12";
    src = fetchFromGitHub {
      owner = "westerndigitalcorporation";
      repo = "ufs-utils";
      rev = "v7.14.12";
      fetchSubmodules = false;
      sha256 = "sha256-/WImgvbyM+xphyUwfkCgUly/lrv8WSQ6rLC54PyCwdE=";
    };
  };
  wayland-book = {
    pname = "wayland-book";
    version = "bec46606567adb6fd11ddf7e01878ac8155d9cf1";
    src = fetchgit {
      url = "https://git.sr.ht/~sircmpwn/wayland-book";
      rev = "bec46606567adb6fd11ddf7e01878ac8155d9cf1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O1DvCvzxkzjtoYykcpltNVuXyJZvD/JAppfez8hY7D0=";
    };
    date = "2024-02-08";
  };
  wiwikwlh = {
    pname = "wiwikwlh";
    version = "7d125ecde6b95e8e39d84a7225b2e8420b744c48";
    src = fetchFromGitHub {
      owner = "sdiehl";
      repo = "wiwinwlh";
      rev = "7d125ecde6b95e8e39d84a7225b2e8420b744c48";
      fetchSubmodules = false;
      sha256 = "sha256-zoSSKHCpWI58cFgE9Y2e5T2KjCZnch5igvxGlcMCeww=";
    };
    date = "2025-09-13";
  };
}
