# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  armake2 = {
    pname = "armake2";
    version = "3cc3362101900ff41504db3e780dd1625634cf94";
    src = fetchFromGitHub {
      owner = "KoffeinFlummi";
      repo = "armake2";
      rev = "3cc3362101900ff41504db3e780dd1625634cf94";
      fetchSubmodules = false;
      sha256 = "sha256-NdJBYvxkQ3yCd5mjwPx4jqEz153fT3B9xglbcJWT02M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-NdJBYvxkQ3yCd5mjwPx4jqEz153fT3B9xglbcJWT02M=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-07-17";
  };
  kindle-tool = {
    pname = "kindle-tool";
    version = "v1.6.6";
    src = fetchFromGitHub {
      owner = "NiLuJe";
      repo = "KindleTool";
      rev = "v1.6.6";
      fetchSubmodules = false;
      sha256 = "sha256-IelccR8b6btLiiJQ5gXyizSIgfZzQtztV5QT3eCHBms=";
    };
  };
  matrix-qq = {
    pname = "matrix-qq";
    version = "0.1.11";
    src = fetchFromGitHub {
      owner = "duo";
      repo = "matrix-qq";
      rev = "0.1.11";
      fetchSubmodules = false;
      sha256 = "sha256-8QY5rySBJ+FSH8uEHewFX7WqhpbzZL1+fMEduDPHu9U=";
    };
  };
  mautrix-telegram = {
    pname = "mautrix-telegram";
    version = "v0.2607.0";
    src = fetchFromGitHub {
      owner = "mautrix";
      repo = "telegram";
      rev = "v0.2607.0";
      fetchSubmodules = false;
      sha256 = "sha256-MpdsWtEsVnC6purF5sw+RD+Nb/3Wo0xrzSn2BuFZmj8=";
    };
  };
  mdbook-epub = {
    pname = "mdbook-epub";
    version = "v0.5.4";
    src = fetchFromGitHub {
      owner = "Michael-F-Bryan";
      repo = "mdbook-epub";
      rev = "v0.5.4";
      fetchSubmodules = false;
      sha256 = "sha256-nAXImr/sRSHcs21X5De3Lt7iTQoVTf18F5VNgzebEUY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-nAXImr_sRSHcs21X5De3Lt7iTQoVTf18F5VNgzebEUY=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  opencl-benchmark = {
    pname = "opencl-benchmark";
    version = "v2.0";
    src = fetchFromGitHub {
      owner = "ProjectPhysX";
      repo = "OpenCL-Benchmark";
      rev = "v2.0";
      fetchSubmodules = false;
      sha256 = "sha256-Z5fH7Rm5JfzObmtSNvvM3Jy5ji1FHvuc1SE98aD1dUY=";
    };
  };
  pandoc-static-amd64 = {
    pname = "pandoc-static-amd64";
    version = "3.10.2";
    src = fetchTarball {
      url = "https://github.com/jgm/pandoc/releases/download/3.10.2/pandoc-3.10.2-linux-amd64.tar.gz";
      sha256 = "sha256-qjXV4n/7TISWbDbq0Y+RBG9kvZDUj4JO1ZNvAKKZ0ws=";
    };
  };
  pandoc-static-arm64 = {
    pname = "pandoc-static-arm64";
    version = "3.10.2";
    src = fetchTarball {
      url = "https://github.com/jgm/pandoc/releases/download/3.10.2/pandoc-3.10.2-linux-arm64.tar.gz";
      sha256 = "sha256-pWe503rbORYz+YnwUtctBSONwjSFLDYfQHOEA64lzGA=";
    };
  };
  piqueserver = {
    pname = "piqueserver";
    version = "bc57bfe30f8bf98209cd90e3bd148981fb232033";
    src = fetchFromGitHub {
      owner = "piqueserver";
      repo = "piqueserver";
      rev = "bc57bfe30f8bf98209cd90e3bd148981fb232033";
      fetchSubmodules = false;
      sha256 = "sha256-Fz8vMZQG1/CM+Qe8VnwHb7VeU+PlJe9mazuO5PeFzns=";
    };
    date = "2026-07-15";
  };
  pyenet = {
    pname = "pyenet";
    version = "1.3.17";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pyenet/pyenet-1.3.17.tar.gz";
      sha256 = "sha256-gOGWDztJfuYB1gnakdwHPCu6jn8FUotnIGuKoM5PGmo=";
    };
  };
  rescript-language-server = {
    pname = "rescript-language-server";
    version = "1.74.0";
    src = fetchFromGitHub {
      owner = "rescript-lang";
      repo = "rescript-vscode";
      rev = "1.74.0";
      fetchSubmodules = false;
      sha256 = "sha256-NIWCxS6Mar7c7l+pdnm+G4U8KEsUsr9pnNaEuvABcvk=";
    };
  };
  rime-table-bin-decompiler = {
    pname = "rime-table-bin-decompiler";
    version = "c722c060f77c3895564d40bd7e3f44a2b315ee7c";
    src = fetchFromGitHub {
      owner = "kitty-panics";
      repo = "rime-table-bin-decompiler";
      rev = "c722c060f77c3895564d40bd7e3f44a2b315ee7c";
      fetchSubmodules = false;
      sha256 = "sha256-2j9c9m4DvsI7jb6RnGiVtzig2qSVRCZEJL47h0Qe09o=";
    };
    date = "2022-10-30";
  };
  rust-async-book = {
    pname = "rust-async-book";
    version = "43891cedf954e991657ba97c2e3ba743d97827ce";
    src = fetchFromGitHub {
      owner = "rust-lang";
      repo = "async-book";
      rev = "43891cedf954e991657ba97c2e3ba743d97827ce";
      fetchSubmodules = false;
      sha256 = "sha256-Wi3DGbwHfKAjqn0lyICrm7BoSIzU2HI4M/O0ww+QMGw=";
    };
    date = "2026-05-25";
  };
  rust-reference = {
    pname = "rust-reference";
    version = "6a5392a7d2e429766a9e128d3bebcd981514f29e";
    src = fetchFromGitHub {
      owner = "rust-lang";
      repo = "reference";
      rev = "6a5392a7d2e429766a9e128d3bebcd981514f29e";
      fetchSubmodules = false;
      sha256 = "sha256-yVH1qTl3v08b8RqMbld7EFGIRX9SIKUBPCslNjUn2/U=";
    };
    date = "2026-08-11";
  };
  rust-rfcs = {
    pname = "rust-rfcs";
    version = "9690d9d93c14611676477f7943f24cc38e2fad39";
    src = fetchFromGitHub {
      owner = "rust-lang";
      repo = "rfcs";
      rev = "9690d9d93c14611676477f7943f24cc38e2fad39";
      fetchSubmodules = false;
      sha256 = "sha256-/xADzqz/UmmBWvoEPWI6cLeKIe762iid7ev48jPVi90=";
    };
    date = "2026-08-10";
  };
  torrent-file-editor = {
    pname = "torrent-file-editor";
    version = "v1.0.3";
    src = fetchFromGitHub {
      owner = "torrent-file-editor";
      repo = "torrent-file-editor";
      rev = "v1.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-iq980BF0IkTVAGtP4s37+0w012cKWIrbNGUmpAzbcg4=";
    };
  };
  transfersh = {
    pname = "transfersh";
    version = "v1.6.1";
    src = fetchFromGitHub {
      owner = "dutchcoders";
      repo = "transfer.sh";
      rev = "v1.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-V8E6RwzxKB6KeGPer5074e7y6XHn3ZD24PQMwTxw5lQ=";
    };
  };
  ufs-utils = {
    pname = "ufs-utils";
    version = "v7.14.12";
    src = fetchFromGitHub {
      owner = "westerndigitalcorporation";
      repo = "ufs-utils";
      rev = "v7.14.12";
      fetchSubmodules = false;
      sha256 = "sha256-/WImgvbyM+xphyUwfkCgUly/lrv8WSQ6rLC54PyCwdE=";
    };
  };
  waybar = {
    pname = "waybar";
    version = "6c3bd01bae35f2ba46cc3b25f95a028861112295";
    src = fetchFromGitHub {
      owner = "Alexays";
      repo = "waybar";
      rev = "6c3bd01bae35f2ba46cc3b25f95a028861112295";
      fetchSubmodules = false;
      sha256 = "sha256-uFfKkAbLn4AgX0uZWlYNUxRUOdRp0x4WKXiOvQqhyy4=";
    };
    date = "2026-08-13";
  };
  wayland-book = {
    pname = "wayland-book";
    version = "7d431b34e8ce946ae7f5b17889e891de98e8305a";
    src = fetchgit {
      url = "https://git.sr.ht/~sircmpwn/wayland-book";
      rev = "7d431b34e8ce946ae7f5b17889e891de98e8305a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5R6muR1Ajm9YHjKNsmV7Q9R4mbG4Y5mGafbDsgUYJVw=";
    };
    date = "2026-08-03";
  };
  wiwikwlh = {
    pname = "wiwikwlh";
    version = "7d125ecde6b95e8e39d84a7225b2e8420b744c48";
    src = fetchFromGitHub {
      owner = "sdiehl";
      repo = "wiwinwlh";
      rev = "7d125ecde6b95e8e39d84a7225b2e8420b744c48";
      fetchSubmodules = false;
      sha256 = "sha256-zoSSKHCpWI58cFgE9Y2e5T2KjCZnch5igvxGlcMCeww=";
    };
    date = "2025-09-13";
  };
}
