[language.racket]
filetypes = [ "racket" ]
roots = [ ".git" ]
command = "racket"
args = [ "-l", "racket-langserver" ]

[language.haskell]
filetypes = [ "haskell" ]
roots = [ "hie.yaml", "cabal.project", "Setup.hs", "stack.yaml", "*.cabal" ]
command = "haskell-language-server-wrapper"
args = [ "--lsp" ]
