name: "cachix"
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - uses: docker/setup-qemu-action@v3
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v12
      with:
        name: nicpkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build .#everything
    - run: nix build .#packages.aarch64-linux.everything --extra-platforms aarch64-linux
