name: "cachix_arm64"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  cachix_arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: "extra-platforms = aarch64-linux"
    - uses: cachix/cachix-action@v14
      with:
        name: nicpkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        useDaemon: false
    - run: |
        nix run .#packages.aarch64-linux.push-to-cachix https://nicpkgs.cachix.org nicpkgs
