name: "cachix-x86_64"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  cachix-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - name: Set Swap
      shell: bash
      run: |
        SWAP_FILE=/swapfile
        sudo fallocate -l 20G $SWAP_FILE
        sudo chmod 600 $SWAP_FILE
        sudo mkswap $SWAP_FILE
        sudo swapon $SWAP_FILE
        free -h
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: nicpkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix run .#build-everything-unsubstitutable https://nicpkgs.cachix.org
