name: "cachix_arm64"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  cachix_arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - uses: docker/setup-qemu-action@v3
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: nicpkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix run --extra-platforms aarch64-linux .#packages.aarch64-linux.build-everything-unsubstitutable https://nicpkgs.cachix.org \
          "nix build --extra-platforms aarch64-linux .#packages.aarch64-linux."
