name: "cachix-x86_64"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  cachix-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
    - uses: docker/setup-qemu-action@v3
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: nicpkgs
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix run .#build-everything-unsubstitutable https://nicpkgs.cachix.org
