name: "Check new factorio versions"
on:
  workflow_dispatch:
jobs:
  update-factorio:
    runs-on: ubuntu-latest
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.FACTORIO_UPDATE_TOKEN }}
    - name: Update script
      run: ./pkgs/factorio-headless/update.py
    - name: Commit & Push
      run: |
        git config --global user.name "Nick Ballard"
        git config --global user.email "znhihgiasy@gmail.com"
        if git commit -am "Automatically update factorio version."; then
          git push
        fi
